#pragma once

#include "targetver.h"
#include <stdio.h>
#include <tchar.h>
#include <fcntl.h>
#include <io.h>
#include <set>
#include <map>
#include <vector>
#include <iostream>
#include <list>
#include <string>
#include <utility>
#include <algorithm>
#include <time.h>
#include <fstream>
#include <sstream>
#include <iomanip>
#include <windows.h>
